apiVersion: v1
kind: ConfigMap
metadata:
  name: prompt-benchmark-config
  namespace: prompt-benchmark
data:
  LLM_PROVIDER: "mock"
  PEB_UI_LANGUAGE: "hu"
  STREAMLIT_BROWSER_GATHER_USAGE_STATS: "false"
