from __future__ import annotations

from dataclasses import dataclass
from typing import Iterable

from rag_engine.presets import CHUNKING_STRATEGIES, CONTEXT_PROFILES, PROMPT_PROFILES, RAG_STRATEGIES


@dataclass(frozen=True)
class ReferenceEntry:
    key: str
    name: str
    category: str
    kind: str
    definition: str
    why_it_matters: str
    interpretation: str = ""
    formula: str | None = None
    unit: str | None = None
    direction: str = "context"
    project_area: tuple[str, ...] = ()
    related: tuple[str, ...] = ()
    caveat: str | None = None


CATEGORY_ORDER = [
    "Adat-előkészítés",
    "Darabolás",
    "Beágyazás és hasonlóság",
    "Vektoradatbázis",
    "Visszakeresés",
    "Újrarangsorolás",
    "Kontextus és prompt",
    "RAG stratégiák",
    "Retrieval metrikák",
    "RAG és groundedness metrikák",
    "Teljesítmény és erőforrás",
    "Kísérletek és reprodukálhatóság",
    "Infrastruktúra",
]

CATEGORY_DESCRIPTIONS = {
    "Adat-előkészítés": "A dokumentumok letöltésétől a tisztított, provenance-információval ellátott szövegig.",
    "Darabolás": "Hogyan lesz a hosszú dokumentumból jól visszakereshető szövegrész.",
    "Beágyazás és hasonlóság": "Szöveg → numerikus vektor, majd vektorok közötti hasonlóság.",
    "Vektoradatbázis": "Embeddingek indexelése és gyors nearest-neighbor keresése FAISS-szal.",
    "Visszakeresés": "A kérdéshez leginkább releváns evidence-jelöltek kiválasztása.",
    "Újrarangsorolás": "A candidate pool finomabb sorrendezése a végső Top-K előtt.",
    "Kontextus és prompt": "A retrieved evidence kiválasztása, promptba rendezése és grounded generation.",
    "RAG stratégiák": "A projektben összehasonlítható RAG-architektúrák és tipikus használatuk.",
    "Retrieval metrikák": "A visszakeresés találati és rangsorolási minőségének mérőszámai.",
    "RAG és groundedness metrikák": "A generált válasz forráskövetésének és evidence-használatának proxyi.",
    "Teljesítmény és erőforrás": "Latency, throughput, TTFT, RAM/VRAM és CPU/CUDA teljesítmény.",
    "Kísérletek és reprodukálhatóság": "Runok, konfigurációhash, dataset fingerprint és A/B összehasonlítás.",
    "Infrastruktúra": "PyTorch CUDA, FAISS, Ollama, kvantálás és runtime-eszközök kapcsolata.",
}


_BASE_ENTRIES: list[ReferenceEntry] = [
    # Data preparation
    ReferenceEntry(
        "ingestion",
        "Dokumentum-ingestion",
        "Adat-előkészítés",
        "Fogalom",
        "A forrásdokumentumok begyűjtésének, letöltésének, beolvasásának és a feldolgozási pipeline-ba emelésének folyamata.",
        "A retrieval minősége nem lehet jobb annál az információnál, amit megbízhatóan és reprodukálhatóan bejuttattunk a rendszerbe.",
        project_area=("Dokumentumok", "Teljes pipeline benchmark"),
        related=("Parsing", "Provenance", "Idempotencia"),
    ),
    ReferenceEntry(
        "parsing",
        "Parsing / szövegkinyerés",
        "Adat-előkészítés",
        "Fogalom",
        "A PDF, HTML, DOCX vagy TXT nyers tartalmának strukturált szöveggé és metaadattá alakítása.",
        "A rossz parser elveszíthet címsorokat, oldalszámokat vagy mondathatárokat, ami később közvetlenül rontja a chunkingot és retrievalt.",
        project_area=("Dokumentumok", "Teljesítmény"),
        related=("Metadata", "Cleaning", "Structure-aware chunking"),
    ),
    ReferenceEntry(
        "cleaning",
        "Adattisztítás",
        "Adat-előkészítés",
        "Fogalom",
        "A felesleges HTML-elemek, hibás whitespace, ismétlődések, zajos karakterek és egyéb nem informatív tartalom eltávolítása.",
        "Kevesebb zaj általában jobb embeddinget, tisztább BM25 jelet és kisebb kontextuspazarlást eredményez.",
        project_area=("Dokumentumok", "Teljes pipeline benchmark"),
        related=("Normalizálás", "Deduplikáció"),
    ),
    ReferenceEntry(
        "normalization",
        "Normalizálás",
        "Adat-előkészítés",
        "Fogalom",
        "A szöveg reprezentációjának egységesítése, például whitespace, Unicode és tipográfiai eltérések kezelése.",
        "Csökkenti az olyan mesterséges különbségeket, amelyek nem szemantikaiak, mégis befolyásolhatják a keresést vagy deduplikációt.",
        project_area=("Dokumentumok",),
        related=("Cleaning", "Deduplikáció"),
    ),
    ReferenceEntry(
        "deduplication",
        "Deduplikáció",
        "Adat-előkészítés",
        "Fogalom",
        "Az azonos vagy közel azonos dokumentumrészek felismerése és ismétlődésük csökkentése.",
        "A duplikált tartalom torzíthatja a Top-K találati listát, felesleges embeddingköltséget okoz és túlreprezentálhat egyetlen forrást.",
        project_area=("Dokumentumok", "Kiértékelés"),
        related=("Duplicate ratio", "SHA-256"),
    ),
    ReferenceEntry(
        "metadata",
        "Metadata",
        "Adat-előkészítés",
        "Fogalom",
        "A szöveghez kapcsolódó strukturált kísérőadat, például cím, URL, oldal, szekció, forrásazonosító és verzió.",
        "Lehetővé teszi a forráskövetést, filterezést, citation megjelenítést és parent-child kapcsolatokat.",
        project_area=("Dokumentumok", "Visszakeresés", "RAG játszótér"),
        related=("Provenance", "Citation"),
    ),
    ReferenceEntry(
        "provenance",
        "Provenance / származás",
        "Adat-előkészítés",
        "Fogalom",
        "Annak rögzítése, hogy egy feldolgozott szövegrész pontosan mely eredeti forrásból és feldolgozási verzióból származik.",
        "A grounded RAG egyik alapja: a válasz csak akkor ellenőrizhető, ha az evidence visszaköthető az eredeti dokumentumhoz.",
        project_area=("Dokumentumok", "RAG játszótér", "Kísérletek"),
        related=("Metadata", "SHA-256", "Citation"),
    ),
    ReferenceEntry(
        "sha256",
        "SHA-256 fingerprint",
        "Adat-előkészítés",
        "Fogalom",
        "Kriptográfiai hash, amellyel a fájl vagy dataset tartalmának változása stabilan detektálható.",
        "Segít eldönteni, kell-e újraparsolni vagy újraindexelni, és az experimenteknél azonosíthatóvá teszi a pontos dataset-verziót.",
        project_area=("Dokumentumok", "Kísérletek"),
        related=("Dataset hash", "Idempotencia"),
    ),
    ReferenceEntry(
        "idempotency",
        "Idempotens feldolgozás",
        "Adat-előkészítés",
        "Fogalom",
        "Ugyanazon bemenet ismételt futtatása nem hoz létre felesleges duplikátumokat vagy eltérő állapotot.",
        "Fontos reprodukálható ingestion és újraindexelés esetén, különösen nagyobb korpuszoknál.",
        project_area=("Dokumentumok", "Infrastruktúra"),
        related=("SHA-256 fingerprint", "Incrementális indexelés"),
    ),
    # Chunking
    ReferenceEntry(
        "chunk",
        "Szövegrész / chunk",
        "Darabolás",
        "Fogalom",
        "A dokumentum kisebb, önállóan indexelhető és visszakereshető szövegegysége.",
        "Túl nagy chunk zajos retrievalt és drága kontextust, túl kicsi chunk kontextusvesztést okozhat.",
        project_area=("Darabolás", "Visszakeresés", "RAG"),
        related=("Chunk size", "Chunk overlap", "Top-K"),
    ),
    ReferenceEntry(
        "chunk_size",
        "Chunk size",
        "Darabolás",
        "Paraméter",
        "A célzott szövegrész-méret karakterben vagy tokenben, a választott splitter típusától függően.",
        "Meghatározza a retrieval granularitását és az egy találatra jutó kontextus mennyiségét.",
        unit="karakter / token",
        project_area=("Darabolás", "Teljes pipeline benchmark"),
        related=("Chunk overlap", "Context budget"),
    ),
    ReferenceEntry(
        "chunk_overlap",
        "Chunk overlap",
        "Darabolás",
        "Paraméter",
        "Az egymást követő chunkok között szándékosan megismételt szövegmennyiség.",
        "Segít megőrizni a határon átnyúló összefüggéseket, de növeli az index méretét és a redundanciát.",
        unit="karakter / token",
        project_area=("Darabolás", "Teljes pipeline benchmark"),
        related=("Duplicate ratio", "Chunk size"),
    ),
    # Embeddings
    ReferenceEntry(
        "embedding",
        "Embedding",
        "Beágyazás és hasonlóság",
        "Fogalom",
        "Szöveg fix dimenziós numerikus vektorreprezentációja, amelyben a szemantikailag hasonló tartalmak jellemzően közelebb kerülnek egymáshoz.",
        "A dense retrieval alapja: a query és a dokumentumchunkok ugyanabban a vektortérben hasonlíthatók össze.",
        project_area=("Beágyazás", "Visszakeresés", "Teljesítmény"),
        related=("Vektortér", "Cosine similarity", "Dense retrieval"),
    ),
    ReferenceEntry(
        "vector_space",
        "Vektortér",
        "Beágyazás és hasonlóság",
        "Fogalom",
        "Az embeddingvektorok matematikai tere, ahol a pozíciók és irányok a modell által tanult reprezentációt hordozzák.",
        "A hasonlósági metrikák ebben a térben értelmezik, mely szövegek vannak közel egymáshoz.",
        project_area=("Beágyazás",),
        related=("Dimenzió", "Cosine similarity"),
    ),
    ReferenceEntry(
        "embedding_dimension",
        "Embedding dimenzió",
        "Beágyazás és hasonlóság",
        "Fogalom",
        "Az embeddingvektor komponenseinek száma.",
        "Nagyobb dimenzió nagyobb reprezentációs kapacitást jelenthet, de több memória- és számítási költséggel jár.",
        unit="dimenzió",
        project_area=("Beágyazás", "Teljesítmény"),
        related=("Embedding", "Index méret"),
    ),
    ReferenceEntry(
        "l2_normalization",
        "L2-normalizálás",
        "Beágyazás és hasonlóság",
        "Fogalom",
        "A vektor skálázása úgy, hogy az euklideszi normája 1 legyen.",
        "Normalizált vektoroknál a dot product és cosine similarity rangsora ekvivalenssé válik.",
        formula=r"\hat{x}=\frac{x}{\lVert x\rVert_2}",
        direction="context",
        project_area=("Beágyazás", "FAISS"),
        related=("Cosine similarity", "Dot product"),
    ),
    ReferenceEntry(
        "cosine_similarity",
        "Cosine similarity",
        "Beágyazás és hasonlóság",
        "Metrika",
        "Két vektor iránya közötti hasonlóságot méri a köztük lévő szög alapján.",
        "Szövegembeddingeknél gyakori hasonlósági mérőszám, mert kevésbé érzékeny a vektorhosszra.",
        interpretation="Nagyobb érték általában nagyobb szemantikai hasonlóságot jelent.",
        formula=r"\cos(\theta)=\frac{x\cdot y}{\lVert x\rVert_2\lVert y\rVert_2}",
        direction="up",
        project_area=("Beágyazás", "Visszakeresés"),
        related=("Dot product", "L2-normalizálás"),
    ),
    ReferenceEntry(
        "dot_product",
        "Dot product / skalárszorzat",
        "Beágyazás és hasonlóság",
        "Metrika",
        "A két vektor komponensenkénti szorzatának összege.",
        "FAISS inner-product indexeknél közvetlen scoringként használható; normalizált vektoroknál cosine rangsort ad.",
        formula=r"x\cdot y=\sum_i x_i y_i",
        direction="up",
        project_area=("FAISS", "Visszakeresés"),
        related=("Cosine similarity", "IndexFlatIP"),
    ),
    ReferenceEntry(
        "euclidean_distance",
        "Euklideszi távolság (L2)",
        "Beágyazás és hasonlóság",
        "Metrika",
        "Két vektor közötti egyenes vonalú távolság.",
        "Egyes embeddingmodelleknél vagy indexeknél természetes távolságmérték, de a jelentése függ a modell tréningjétől és normalizálástól.",
        formula=r"d(x,y)=\sqrt{\sum_i(x_i-y_i)^2}",
        direction="down",
        project_area=("Beágyazás", "Vektoradatbázis"),
        related=("Cosine similarity",),
    ),
    ReferenceEntry(
        "multilingual_embedding",
        "Multilingual embedding",
        "Beágyazás és hasonlóság",
        "Fogalom",
        "Több nyelv szövegeit közös szemantikai vektortérbe képező embeddingmodell.",
        "Magyar korpusznál fontos, mert a modellnek a magyar morfológiát és szemantikai kapcsolatokat is kezelnie kell.",
        project_area=("Beágyazás", "Teljes pipeline benchmark"),
        related=("E5", "Sentence Transformer"),
    ),
    ReferenceEntry(
        "query_passage_prefix",
        "Query / passage prefix",
        "Beágyazás és hasonlóság",
        "Fogalom",
        "Egyes retrievalre tanított modellek eltérő prefixet várnak a lekérdezéshez és a dokumentumszöveghez, például `query:` és `passage:`.",
        "A helyes prefixelés befolyásolhatja a retrieval qualityt, ezért benchmarknál konzisztensen kell használni.",
        project_area=("Beágyazás", "Teljes pipeline benchmark"),
        related=("E5", "Dense retrieval"),
    ),
    # Vector DB
    ReferenceEntry(
        "faiss",
        "FAISS",
        "Vektoradatbázis",
        "Technológia",
        "Meta által fejlesztett könyvtár nagy dimenziós vektorok hatékony hasonlósági keresésére és indexelésére.",
        "A projekt dense retrieval rétegének lokális, ingyenes és reprodukálható vektorindexe.",
        project_area=("Visszakeresés", "Infrastruktúra", "Teljesítmény"),
        related=("IndexFlatIP", "Vector search"),
    ),
    ReferenceEntry(
        "index_flat_ip",
        "IndexFlatIP",
        "Vektoradatbázis",
        "Fogalom",
        "Exact FAISS index, amely inner product alapján minden releváns vektort közvetlenül összehasonlít.",
        "Kisebb-közepes korpusznál jó baseline, mert nincs approximációs recall-veszteség.",
        direction="context",
        project_area=("Visszakeresés", "Teljesítmény"),
        related=("Dot product", "FAISS"),
    ),
    ReferenceEntry(
        "vector_index_build",
        "Vektorindex építés",
        "Vektoradatbázis",
        "Fogalom",
        "Az embeddingvektorok betöltése és kereshető indexstruktúrába rendezése.",
        "Cold-start, újraindexelés és corpus-frissítés esetén külön teljesítményköltség.",
        project_area=("Teljesítmény", "Teljes pipeline benchmark"),
        related=("Embedding throughput", "Index build latency"),
    ),
    # Retrieval
    ReferenceEntry(
        "query",
        "Lekérdezés / query",
        "Visszakeresés",
        "Fogalom",
        "A felhasználói információigény keresésre átadott reprezentációja.",
        "A retrieval minden ranking döntése ehhez viszonyítja a dokumentumchunkokat.",
        project_area=("Visszakeresés", "RAG"),
        related=("Query rewrite", "Multi-Query"),
    ),
    ReferenceEntry(
        "dense_retrieval",
        "Dense retrieval",
        "Visszakeresés",
        "Stratégia",
        "A query és a dokumentumchunkok embeddingjei közötti vektorhasonlóság alapján rangsorol.",
        "Jól kezeli a szemantikai hasonlóságot akkor is, ha a kérdés és a forrás nem ugyanazokat a szavakat használja.",
        project_area=("Visszakeresés", "Kiértékelés"),
        related=("Embedding", "FAISS"),
    ),
    ReferenceEntry(
        "bm25",
        "BM25",
        "Visszakeresés",
        "Stratégia",
        "Lexikális rangsorolási függvény, amely a query szavainak dokumentumbeli gyakoriságát, ritkaságát és a dokumentumhosszt kombinálja.",
        "Erős pontos terminusoknál, rövidítéseknél, gyógyszer- vagy betegségneveknél, ahol a konkrét szóegyezés fontos.",
        project_area=("Visszakeresés", "RAG összehasonlítás"),
        related=("Sparse retrieval", "Hybrid retrieval"),
    ),
    ReferenceEntry(
        "hybrid_retrieval",
        "Hibrid retrieval",
        "Visszakeresés",
        "Stratégia",
        "Dense és lexikális visszakeresés eredményeinek kombinálása.",
        "A szemantikus és pontos kulcsszavas jeleket együtt használja, ezért heterogén korpuszon stabilabb lehet.",
        project_area=("Visszakeresés", "RAG összehasonlítás", "Teljes pipeline benchmark"),
        related=("Dense retrieval", "BM25", "RRF"),
    ),
    ReferenceEntry(
        "rrf",
        "Reciprocal Rank Fusion (RRF)",
        "Visszakeresés",
        "Stratégia",
        "Több rangsor pozícióit kombináló rank-fúziós módszer, amely nem igényli a score-skálák közvetlen összehasonlíthatóságát.",
        "Kifejezetten hasznos dense és BM25 lista összeolvasztására, mert a két score különböző skálán mozoghat.",
        formula=r"RRF(d)=\sum_r \frac{1}{k+rank_r(d)}",
        direction="up",
        project_area=("Visszakeresés", "Teljes pipeline benchmark"),
        related=("Hybrid retrieval", "RRF k"),
    ),
    ReferenceEntry(
        "top_k",
        "Top-K",
        "Visszakeresés",
        "Paraméter",
        "A rankingből továbbadott legjobb K találat száma.",
        "Nagyobb K javíthatja a recallt, de több zajt és nagyobb context budgetet eredményezhet.",
        unit="találat",
        project_area=("Visszakeresés", "RAG", "Kiértékelés"),
        related=("Recall@K", "Precision@K", "Candidate pool"),
    ),
    ReferenceEntry(
        "candidate_pool",
        "Candidate pool",
        "Visszakeresés",
        "Fogalom",
        "A reranker elé továbbított, a végső Top-K-nál nagyobb jelöltkészlet.",
        "Lehetővé teszi, hogy a második körös rangsoroló javítson az első retrieval sorrendjén.",
        project_area=("Visszakeresés", "Újrarangsorolás"),
        related=("Reranker", "Top-K"),
    ),
    ReferenceEntry(
        "source_diversity",
        "Forrásdiverzitás",
        "Visszakeresés",
        "Metrika",
        "A Top-K találatokban megjelenő különböző forrásdokumentumok aránya vagy száma.",
        "Segít felismerni, ha a retrieval listát egyetlen dokumentum duplikált vagy nagyon hasonló chunkjai uralják.",
        interpretation="Nagyobb érték gyakran hasznos, de nem minden kérdés igényel több forrást.",
        direction="context",
        project_area=("Kiértékelés", "RAG"),
        related=("Duplicate ratio", "Top-K"),
    ),
    # Reranking
    ReferenceEntry(
        "reranker",
        "Újrarangsoroló / reranker",
        "Újrarangsorolás",
        "Fogalom",
        "A retrieval candidate pool második körös sorrendezője, amely a query–chunk kapcsolatot finomabban értékeli.",
        "A retrieval recall megtartása mellett javíthatja, hogy a legjobb evidence-ek kerüljenek a szűk LLM-kontextusba.",
        project_area=("Visszakeresés", "RAG", "Teljesítmény"),
        related=("Candidate pool", "Cross-Encoder"),
    ),
    ReferenceEntry(
        "cross_encoder",
        "Cross-Encoder",
        "Újrarangsorolás",
        "Technológia",
        "A queryt és a candidate szöveget együtt kódoló modell, amely közvetlen relevancia-pontszámot ad a párra.",
        "Általában pontosabb, mint pusztán két külön embedding hasonlósága, de jelentősen drágább lehet.",
        project_area=("Visszakeresés", "Teljesítmény", "Teljes pipeline benchmark"),
        related=("Reranker", "CUDA"),
    ),
    ReferenceEntry(
        "lexical_reranker",
        "Lexikális újrarangsorolás",
        "Újrarangsorolás",
        "Stratégia",
        "Könnyű, szövegátfedésen alapuló második körös rangsorolás.",
        "Jó olcsó baseline, amikor Cross-Encoder nem kívánatos vagy nem fér bele a latency budgetbe.",
        project_area=("RAG", "Teljesítmény"),
        related=("Cross-Encoder", "Reranking latency"),
    ),
    # Context / prompting
    ReferenceEntry(
        "context_window",
        "Kontextusablak",
        "Kontextus és prompt",
        "Fogalom",
        "Az LLM által egy generálási kérésben kezelhető teljes tokenmennyiség, beleértve az utasítást, kérdést, evidence-et és választeret.",
        "Meghatározza, mennyi retrieved evidence fér be egyszerre, és közvetlenül hat a memória- és latency-költségre.",
        unit="token",
        project_area=("RAG", "Infrastruktúra"),
        related=("Context budget", "KV cache"),
    ),
    ReferenceEntry(
        "context_budget",
        "Kontextuskeret / context budget",
        "Kontextus és prompt",
        "Paraméter",
        "A teljes kontextusablakból retrieval evidence-re szánt tokenkeret.",
        "Kontrollálja a prompt méretét és azt, hogy mennyi forrásrészlet kerül az LLM elé.",
        unit="token",
        project_area=("RAG", "Teljes pipeline benchmark"),
        related=("Kontextusablak", "Context builder"),
    ),
    ReferenceEntry(
        "context_builder",
        "Context builder",
        "Kontextus és prompt",
        "Fogalom",
        "A retrieved chunkokból a tokenbudget figyelembevételével összeállítja a végső, rendezett LLM-kontextust.",
        "A jó context builder deduplikál, priorizál, forrásazonosítókat ad és nem tölti tele a promptot irreleváns szöveggel.",
        project_area=("RAG játszótér", "RAG összehasonlítás"),
        related=("Context budget", "Evidence"),
    ),
    ReferenceEntry(
        "evidence",
        "Evidence / forrásbizonyíték",
        "Kontextus és prompt",
        "Fogalom",
        "A retrievalből származó konkrét szövegrész, amely a válasz egy vagy több állítását alátámaszthatja.",
        "A grounded generationben a válasz nem pusztán a modell paraméteres tudására, hanem ellenőrizhető evidence-re támaszkodik.",
        project_area=("RAG játszótér", "Kiértékelés"),
        related=("Citation", "Grounded prompt"),
    ),
    ReferenceEntry(
        "grounded_prompt",
        "Forrásokra támaszkodó prompt",
        "Kontextus és prompt",
        "Fogalom",
        "Olyan prompt, amely explicit evidence-blokkot és olyan utasítást ad az LLM-nek, hogy a választ a megadott forrásokra alapozza.",
        "Csökkenti a forrás nélküli állítások kockázatát és megteremti a citation-alapú auditálhatóságot.",
        project_area=("RAG játszótér", "RAG összehasonlítás"),
        related=("Evidence", "Citation", "Prompt profile"),
    ),
    ReferenceEntry(
        "citation",
        "Hivatkozás / citation",
        "Kontextus és prompt",
        "Fogalom",
        "A válaszban elhelyezett jelölés, például [S1], amely egy konkrét retrieved evidence-re mutat.",
        "Lehetővé teszi a válasz állításainak visszaellenőrzését és a forráskövetést.",
        project_area=("RAG játszótér", "Kiértékelés"),
        related=("Citation accuracy", "Evidence"),
    ),
    ReferenceEntry(
        "structured_output",
        "Strukturált kimenet",
        "Kontextus és prompt",
        "Fogalom",
        "Az LLM-válasz előre definiált struktúrához, például JSON schema vagy Pydantic modellhez kötött formátuma.",
        "Megbízhatóbb downstream feldolgozást és validálható integrációt tesz lehetővé.",
        project_area=("RAG", "API-integráció"),
        related=("Pydantic", "Validáció"),
    ),
    ReferenceEntry(
        "abstention",
        "Abstention / tartózkodás",
        "Kontextus és prompt",
        "Fogalom",
        "A rendszer kontrolláltan nem ad tartalmi választ, ha nincs elegendő vagy megfelelő evidence.",
        "Grounded rendszernél jobb lehet explicit bizonytalanságot jelezni, mint forrás nélküli választ generálni.",
        project_area=("RAG", "Kiértékelés"),
        related=("Unsupported claim", "Groundedness"),
    ),
    # Retrieval metrics
    ReferenceEntry(
        "recall_at_k",
        "Recall@K",
        "Retrieval metrikák",
        "Metrika",
        "A releváns találatok mekkora részét találta meg a rendszer az első K eredmény között.",
        "Azt méri, mennyi releváns evidence maradt ki a Top-K-ból.",
        interpretation="1.0 azt jelenti, hogy minden ismert releváns elem bekerült a Top-K-ba.",
        formula=r"Recall@K=\frac{|Rel\cap TopK|}{|Rel|}",
        unit="0–1",
        direction="up",
        project_area=("Kiértékelés", "Teljes pipeline benchmark"),
        related=("Precision@K", "Hit Rate@K"),
    ),
    ReferenceEntry(
        "precision_at_k",
        "Precision@K",
        "Retrieval metrikák",
        "Metrika",
        "A Top-K találatok mekkora része releváns.",
        "Azt mutatja, mennyi zaj került a retrieval listába.",
        formula=r"Precision@K=\frac{|Rel\cap TopK|}{K}",
        unit="0–1",
        direction="up",
        project_area=("Kiértékelés",),
        related=("Recall@K", "F1@K"),
    ),
    ReferenceEntry(
        "f1_at_k",
        "F1@K",
        "Retrieval metrikák",
        "Metrika",
        "A Precision@K és Recall@K harmonikus átlaga.",
        "Egyetlen számban egyensúlyozza a retrieval teljességét és tisztaságát.",
        formula=r"F1=2\cdot\frac{Precision\cdot Recall}{Precision+Recall}",
        unit="0–1",
        direction="up",
        project_area=("Kiértékelés",),
        related=("Precision@K", "Recall@K"),
    ),
    ReferenceEntry(
        "hit_rate_at_k",
        "Hit Rate@K",
        "Retrieval metrikák",
        "Metrika",
        "A queryk mekkora részénél van legalább egy releváns találat a Top-K-ban.",
        "Jó egyszerű diagnosztika arra, hogy a retrieval legalább eltalálja-e a megfelelő evidence-környezetet.",
        formula=r"HitRate@K=\frac{1}{N}\sum_q \mathbb{1}[TopK_q\cap Rel_q\neq\emptyset]",
        unit="0–1",
        direction="up",
        project_area=("Kiértékelés",),
        related=("Recall@K",),
    ),
    ReferenceEntry(
        "mrr",
        "MRR – Mean Reciprocal Rank",
        "Retrieval metrikák",
        "Metrika",
        "Az első releváns találat reciprok rangjának átlaga a queryk felett.",
        "Erősen jutalmazza, ha az első jó evidence nagyon előre kerül.",
        formula=r"MRR=\frac{1}{N}\sum_{q=1}^{N}\frac{1}{rank_q}",
        unit="0–1",
        direction="up",
        project_area=("Kiértékelés", "Teljes pipeline benchmark"),
        related=("First relevant rank", "nDCG@K"),
    ),
    ReferenceEntry(
        "average_precision",
        "Average Precision (AP)",
        "Retrieval metrikák",
        "Metrika",
        "Egy query rangsorában minden releváns találati pozíciónál figyelembe veszi az addigi precisiont, majd ezek átlagát számolja.",
        "Több releváns találat esetén informatívabb lehet, mint csak az első releváns pozícióját mérő MRR.",
        formula=r"AP=\frac{1}{|Rel|}\sum_{k=1}^{K}P@k\cdot rel(k)",
        unit="0–1",
        direction="up",
        project_area=("Kiértékelés",),
        related=("MAP@K", "Precision@K"),
    ),
    ReferenceEntry(
        "map_at_k",
        "MAP@K – Mean Average Precision",
        "Retrieval metrikák",
        "Metrika",
        "A querynként számolt Average Precision átlagát adja.",
        "Egyszerre érzékeny arra, hogy hány releváns találat van és azok milyen korán jelennek meg.",
        formula=r"MAP@K=\frac{1}{N}\sum_q AP_q@K",
        unit="0–1",
        direction="up",
        project_area=("Kiértékelés",),
        related=("Average Precision", "nDCG@K"),
    ),
    ReferenceEntry(
        "dcg",
        "DCG – Discounted Cumulative Gain",
        "Retrieval metrikák",
        "Metrika",
        "A relevanciát a rangpozíció logaritmikus büntetésével összegzi.",
        "A lista elején lévő releváns elemek többet érnek, mint ugyanazok hátrébb.",
        formula=r"DCG@K=\sum_{i=1}^{K}\frac{2^{rel_i}-1}{\log_2(i+1)}",
        direction="up",
        project_area=("Kiértékelés",),
        related=("nDCG@K",),
    ),
    ReferenceEntry(
        "ndcg_at_k",
        "nDCG@K",
        "Retrieval metrikák",
        "Metrika",
        "A DCG normalizált változata, amely az ideális rangsorhoz viszonyít.",
        "A relevancia és a sorrend minőségét együtt méri, összehasonlítható 0–1 skálán.",
        formula=r"nDCG@K=\frac{DCG@K}{IDCG@K}",
        unit="0–1",
        direction="up",
        project_area=("Kiértékelés", "Teljes pipeline benchmark"),
        related=("DCG", "MRR"),
    ),
    ReferenceEntry(
        "first_relevant_rank",
        "Első releváns találat rangja",
        "Retrieval metrikák",
        "Metrika",
        "Az első releváns evidence pozíciója a rendezett találati listában.",
        "Közvetlenül megmutatja, mennyire kell mélyre menni a rankingben az első jó találatig.",
        unit="rang",
        direction="down",
        project_area=("Kiértékelés",),
        related=("MRR",),
    ),
    ReferenceEntry(
        "duplicate_ratio",
        "Duplikációs arány@K",
        "Retrieval metrikák",
        "Metrika",
        "A Top-K listán belüli ismétlődő vagy azonos chunkok aránya.",
        "Magas érték arra utalhat, hogy a retrieval kevés információt ismétel túl sok pozícióban.",
        unit="0–1",
        direction="down",
        project_area=("Kiértékelés",),
        related=("Forrásdiverzitás", "Deduplikáció"),
    ),
    ReferenceEntry(
        "label_coverage",
        "Címkézési lefedettség",
        "Retrieval metrikák",
        "Metrika",
        "Az evaluation itemek mekkora részéhez sikerült az aktuális chunking mellett releváns chunkot feloldani a stabil source/evidence információból.",
        "Ha alacsony, a retrieval metrikák részben a labeling pipeline korlátait mérhetik, nem csak a retrievert.",
        unit="0–1",
        direction="up",
        project_area=("Kiértékelés",),
        related=("Evaluation dataset", "Relevant chunk resolution"),
        caveat="Ez a projektben heurisztikus evidence-token overlap feloldást is használhat.",
    ),
    # Groundedness metrics
    ReferenceEntry(
        "citation_accuracy",
        "Hivatkozási pontosság",
        "RAG és groundedness metrikák",
        "Metrika",
        "A válaszban szereplő [Sx] hivatkozások mekkora része mutat ténylegesen létező retrieved evidence-re.",
        "Az érvénytelen vagy nem létező citation jelölések gyorsan kiszűrhetők vele.",
        unit="0–1",
        direction="up",
        project_area=("RAG játszótér", "Kiértékelés"),
        related=("Citation coverage", "Evidence"),
        caveat="Nem bizonyítja, hogy a hivatkozott evidence valóban támogatja az adott állítást.",
    ),
    ReferenceEntry(
        "citation_coverage",
        "Hivatkozási lefedettség",
        "RAG és groundedness metrikák",
        "Metrika",
        "A válasz azon állításainak vagy mondatainak aránya, amelyek explicit source citationt kapnak.",
        "Segít mérni, mennyire következetesen forrásolt a generált válasz.",
        unit="0–1",
        direction="up",
        project_area=("RAG", "Kiértékelés"),
        related=("Citation accuracy",),
        caveat="A projektben transzparens heurisztikus proxy, nem teljes claim-level verifier.",
    ),
    ReferenceEntry(
        "citation_source_coverage",
        "Forráslefedettség",
        "RAG és groundedness metrikák",
        "Metrika",
        "A retrieved források mekkora része jelenik meg ténylegesen citationként a válaszban.",
        "Megmutatja, hogy a rendszer a visszakeresett evidence-ek közül mennyit használt explicit módon.",
        unit="0–1",
        direction="context",
        project_area=("RAG", "Kiértékelés"),
        related=("Citation coverage", "Forrásdiverzitás"),
    ),
    ReferenceEntry(
        "key_fact_coverage",
        "Kulcstény-lefedettség",
        "RAG és groundedness metrikák",
        "Metrika",
        "Az evaluation datasetben rögzített expected key factek mekkora része jelenik meg a válaszban.",
        "A válasz tartalmi teljességének egyszerű, reprodukálható közelítése.",
        unit="0–1",
        direction="up",
        project_area=("Kiértékelés", "Teljes pipeline benchmark"),
        related=("Evaluation dataset", "Answer completeness"),
        caveat="Jelenleg lexikális proxy, ezért nem klinikai correctness vagy szemantikus judge.",
    ),
    ReferenceEntry(
        "context_utilization",
        "Kontextus-kihasználtság",
        "RAG és groundedness metrikák",
        "Metrika",
        "A generált válasz lexikális tartalmának mekkora része fedhető le a retrieved contextből.",
        "Diagnosztikai jel arra, hogy a válasz mennyire támaszkodik a megadott evidence-re.",
        unit="0–1",
        direction="up",
        project_area=("RAG", "Kiértékelés"),
        related=("Grounded prompt", "Key-fact coverage"),
        caveat="Lexikális proxy; nem bizonyítja szemantikusan minden claim támogatását.",
    ),
    ReferenceEntry(
        "answer_redundancy",
        "Válaszredundancia",
        "RAG és groundedness metrikák",
        "Metrika",
        "A válasz ismétlődő mondatait vagy erősen átfedő részeit becslő mutató.",
        "Segít felismerni a túlismétlő generálást és a fölösleges tokenhasználatot.",
        unit="0–1",
        direction="down",
        project_area=("RAG", "Kiértékelés"),
        caveat="A projektben lexikális proxy.",
    ),
    ReferenceEntry(
        "overall_score",
        "Összesített minőségi pontszám",
        "RAG és groundedness metrikák",
        "Összetett metrika",
        "Több részmetrika dokumentált súlyozott kombinációja, amely gyors összefoglaló nézetet ad.",
        "Hasznos konfigurációk szűrésére, de a részmetrikák elemzését nem helyettesíti.",
        interpretation="Retrieval és RAG oldalon eltérő részmetrikákból épül fel.",
        unit="0–1",
        direction="up",
        project_area=("Kiértékelés", "Teljes pipeline benchmark"),
        related=("Hatékonysági pontszám", "nDCG@K"),
    ),
    ReferenceEntry(
        "efficiency_score",
        "Hatékonysági pontszám",
        "RAG és groundedness metrikák",
        "Összetett metrika",
        "A minőségi pontszám és a normalizált latency kombinációja.",
        "Segít olyan konfigurációkat találni, amelyek nem csak jók, hanem a futási költségükhöz képest is hatékonyak.",
        unit="0–1",
        direction="up",
        project_area=("Kiértékelés", "Teljes pipeline benchmark"),
        related=("Összesített minőségi pontszám", "Latency"),
        caveat="A súlyok projekt-specifikusak; nem univerzális iparági standard.",
    ),
    # Performance
    ReferenceEntry(
        "latency",
        "Késleltetés / latency",
        "Teljesítmény és erőforrás",
        "Metrika",
        "Egy művelet vagy teljes kérés végrehajtási ideje.",
        "Felhasználói élmény, skálázhatóság és throughput szempontjából alapvető teljesítménymetrika.",
        unit="ms / s",
        direction="down",
        project_area=("Teljesítmény", "Kiértékelés"),
        related=("P50", "P95", "TTFT"),
    ),
    ReferenceEntry(
        "mean_latency",
        "Átlagos latency",
        "Teljesítmény és erőforrás",
        "Metrika",
        "A mért futásidők számtani átlaga.",
        "Jól összefoglalja az átlagos költséget, de elrejtheti a lassú outliereket.",
        formula=r"\bar{x}=\frac{1}{N}\sum_i x_i",
        unit="ms / s",
        direction="down",
        project_area=("Teljesítmény",),
        related=("P95 latency", "P99 latency"),
    ),
    ReferenceEntry(
        "p50_latency",
        "P50 latency / medián",
        "Teljesítmény és erőforrás",
        "Metrika",
        "Az a latency, amelynél a futások 50%-a gyorsabb vagy azonos.",
        "Stabilabb tipikus válaszidő-mutató, mint az átlag, ha vannak outlierek.",
        unit="ms / s",
        direction="down",
        project_area=("Teljesítmény", "Kiértékelés"),
        related=("P95 latency", "Mean latency"),
    ),
    ReferenceEntry(
        "p95_latency",
        "P95 latency",
        "Teljesítmény és erőforrás",
        "Metrika",
        "Az a latency, amely alatt a futások 95%-a teljesül.",
        "A tail latency egyik legfontosabb operációs mutatója; megmutatja, mit tapasztalnak a lassabb kérések.",
        unit="ms / s",
        direction="down",
        project_area=("Teljesítmény", "Kiértékelés"),
        related=("P99 latency", "Mean latency"),
    ),
    ReferenceEntry(
        "p99_latency",
        "P99 latency",
        "Teljesítmény és erőforrás",
        "Metrika",
        "Az a latency, amely alatt a futások 99%-a teljesül.",
        "A ritka, nagyon lassú esetek és erőforrás-tüskék érzékelésére használható.",
        unit="ms / s",
        direction="down",
        project_area=("Teljesítmény", "Kiértékelés"),
        related=("P95 latency",),
    ),
    ReferenceEntry(
        "throughput",
        "Áteresztőképesség / throughput",
        "Teljesítmény és erőforrás",
        "Metrika",
        "Egységnyi idő alatt feldolgozható elemek száma.",
        "Embeddingnél text/s, retrievalnél query/s, LLM-nél token/s formában jelenhet meg.",
        formula=r"Throughput=\frac{N_{item}}{t_{sec}}",
        direction="up",
        project_area=("Teljesítmény",),
        related=("QPS", "Token/s"),
    ),
    ReferenceEntry(
        "qps",
        "QPS – Queries Per Second",
        "Teljesítmény és erőforrás",
        "Metrika",
        "Másodpercenként feldolgozható lekérdezések száma.",
        "Retrieval throughput összehasonlítására használható különböző backendek és device-ok között.",
        formula=r"QPS=\frac{N_{query}}{t_{sec}}",
        unit="query/s",
        direction="up",
        project_area=("Teljesítmény", "Kiértékelés"),
        related=("Latency", "Throughput"),
    ),
    ReferenceEntry(
        "ttft",
        "TTFT – Time to First Token",
        "Teljesítmény és erőforrás",
        "Metrika",
        "A generálási kérés elküldésétől az első output token megérkezéséig eltelt idő.",
        "Streaming LLM UX esetén ez határozza meg, mennyire gyorsnak érződik a válasz kezdete.",
        unit="ms / s",
        direction="down",
        project_area=("RAG", "Teljesítmény"),
        related=("Token/s", "Generation latency"),
    ),
    ReferenceEntry(
        "tokens_per_second",
        "Token/s",
        "Teljesítmény és erőforrás",
        "Metrika",
        "Az LLM dekódolási sebessége: másodpercenként hány output token készül el.",
        "Közvetlenül jelzi a generálási throughputot, és hardver/modelprofil összehasonlításnál informatív.",
        unit="token/s",
        direction="up",
        project_area=("RAG", "Teljesítmény"),
        related=("TTFT", "Generation latency"),
    ),
    ReferenceEntry(
        "cold_start",
        "Hidegindítás / cold start",
        "Teljesítmény és erőforrás",
        "Metrika",
        "Az első használat extra költsége, például modellbetöltés, CUDA inicializálás vagy index megnyitás miatt.",
        "Az első kérés gyakran jelentősen lassabb, mint a már bemelegített rendszer.",
        unit="ms / s",
        direction="down",
        project_area=("Teljesítmény", "Infrastruktúra"),
        related=("Warm-up", "Model load"),
    ),
    ReferenceEntry(
        "ram",
        "RAM-használat",
        "Teljesítmény és erőforrás",
        "Metrika",
        "A folyamat által használt rendszer-memória mennyisége.",
        "Nagy embeddingmodellek, indexek és dokumentumkorpuszok esetén korlátozó erőforrás lehet.",
        unit="MB / GB",
        direction="down",
        project_area=("Teljesítmény", "Infrastruktúra"),
        related=("VRAM",),
    ),
    ReferenceEntry(
        "vram",
        "VRAM-használat",
        "Teljesítmény és erőforrás",
        "Metrika",
        "A GPU memóriájából felhasznált mennyiség.",
        "A lokális embedding, Cross-Encoder és LLM futtatásnál meghatározza, milyen modell és context fér el stabilan.",
        unit="MB / GB",
        direction="down",
        project_area=("Teljesítmény", "Infrastruktúra"),
        related=("CUDA", "KV cache"),
    ),
    ReferenceEntry(
        "speedup",
        "Gyorsulás / speedup",
        "Teljesítmény és erőforrás",
        "Metrika",
        "Két végrehajtási mód sebességarányának összehasonlítása, például CPU és CUDA között.",
        "Egyszerűen megmutatja, hogy a gyorsító backend mekkora tényleges nyereséget adott ugyanazon workloadon.",
        formula=r"Speedup=\frac{T_{baseline}}{T_{accelerated}}",
        unit="×",
        direction="up",
        project_area=("Teljesítmény",),
        related=("CPU", "CUDA"),
    ),
    # Experiments
    ReferenceEntry(
        "run_id",
        "Run ID",
        "Kísérletek és reprodukálhatóság",
        "Fogalom",
        "Egy konkrét benchmark-futtatás egyedi azonosítója.",
        "Ugyanaz a konfiguráció többször is lefuttatható, miközben minden mérés külön runként visszakereshető.",
        project_area=("Kísérletek",),
        related=("Config hash", "Experiment Registry"),
    ),
    ReferenceEntry(
        "config_hash",
        "Konfigurációhash",
        "Kísérletek és reprodukálhatóság",
        "Fogalom",
        "A benchmark szempontjából releváns konfiguráció determinisztikus fingerprintje.",
        "Gyorsan felismerhető, ha két run ugyanazzal a beállítással készült.",
        project_area=("Kísérletek",),
        related=("Run ID", "Dataset hash"),
    ),
    ReferenceEntry(
        "dataset_hash",
        "Dataset hash",
        "Kísérletek és reprodukálhatóság",
        "Fogalom",
        "Az evaluation dataset tartalmának fingerprintje.",
        "Megakadályozza, hogy két eltérő kérdéskészlet eredményeit észrevétlenül ugyanazon benchmarkként kezeljük.",
        project_area=("Kísérletek", "Kiértékelés"),
        related=("Config hash", "SHA-256 fingerprint"),
    ),
    ReferenceEntry(
        "experiment_registry",
        "Experiment Registry",
        "Kísérletek és reprodukálhatóság",
        "Fogalom",
        "Strukturált adatbázis a benchmark runok, konfigurációk, metrikák, státuszok és hibák tárolására.",
        "Lehetővé teszi az A/B összehasonlítást, historikus elemzést és reprodukálható experiment workflow-t.",
        project_area=("Kísérletek",),
        related=("Run ID", "A/B összehasonlítás"),
    ),
    ReferenceEntry(
        "ab_comparison",
        "A/B összehasonlítás",
        "Kísérletek és reprodukálhatóság",
        "Fogalom",
        "Két konkrét konfiguráció vagy run ugyanazon metrikák szerinti összevetése.",
        "Segít izolálni, hogy egyetlen változtatás milyen quality-, latency- vagy resource-hatást okozott.",
        project_area=("Kísérletek",),
        related=("Delta", "Config diff"),
    ),
    ReferenceEntry(
        "pareto_front",
        "Pareto-front",
        "Kísérletek és reprodukálhatóság",
        "Fogalom",
        "Olyan konfigurációk halmaza, amelyeket nem lehet egy célban javítani anélkül, hogy legalább egy másik cél romlana.",
        "Quality–latency trade-off esetén segít megtalálni a valóban érdekes kompromisszumokat egyetlen önkényes winner helyett.",
        project_area=("Teljes pipeline benchmark", "Kísérletek"),
        related=("Hatékonysági pontszám", "Quality–latency"),
    ),
    ReferenceEntry(
        "regression_gate",
        "Regression gate",
        "Kísérletek és reprodukálhatóság",
        "Fogalom",
        "Automatikus küszöb vagy baseline-összehasonlítás, amely hibának jelöli a lényeges minőségromlást.",
        "CI-ben megakadályozhatja, hogy egy kódváltozás észrevétlenül rontsa a retrieval vagy RAG minőségét.",
        project_area=("CI", "Kiértékelés"),
        related=("Golden set", "Experiment Registry"),
    ),
    # Infrastructure
    ReferenceEntry(
        "cuda",
        "CUDA",
        "Infrastruktúra",
        "Technológia",
        "NVIDIA GPU-k programozási és gyorsítási platformja.",
        "A projektben PyTorch embedding és Cross-Encoder számításokat, illetve az Ollama LLM runtime-ot gyorsíthatja.",
        project_area=("Infrastruktúra", "Teljesítmény"),
        related=("PyTorch CUDA", "VRAM"),
    ),
    ReferenceEntry(
        "pytorch_cuda",
        "PyTorch CUDA build",
        "Infrastruktúra",
        "Fogalom",
        "Olyan PyTorch telepítés, amely CUDA runtime támogatással képes NVIDIA GPU-n tensor műveleteket futtatni.",
        "A `cuda-python` telepítése önmagában nem teszi CUDA-képessé a PyTorchot; a megfelelő PyTorch wheel külön szükséges.",
        project_area=("Infrastruktúra",),
        related=("CUDA", "torch.cuda.is_available"),
    ),
    ReferenceEntry(
        "requested_actual_device",
        "Kért vs tényleges device",
        "Infrastruktúra",
        "Fogalom",
        "A felhasználó által kért végrehajtási eszköz és az a backend, amelyen a művelet ténylegesen lefutott.",
        "Fallback esetén megakadályozza, hogy CPU-n futott eredményt tévesen CUDA benchmarkként értelmezzünk.",
        project_area=("Infrastruktúra", "Teljes pipeline benchmark"),
        related=("CPU fallback", "CUDA"),
    ),
    ReferenceEntry(
        "faiss_cpu",
        "FAISS CPU backend",
        "Infrastruktúra",
        "Fogalom",
        "A FAISS CPU-n futó indeximplementációja.",
        "Windows környezetben ez a projekt stabil baseline-ja; attól még az embedding és reranker futhat CUDA-n.",
        project_area=("Infrastruktúra", "Vektoradatbázis"),
        related=("FAISS", "Kért vs tényleges device"),
    ),
    ReferenceEntry(
        "ollama",
        "Ollama",
        "Infrastruktúra",
        "Technológia",
        "Lokális LLM-ek letöltését, betöltését és HTTP API-n keresztüli futtatását kezelő runtime.",
        "Lehetővé teszi a projekt fizetős API nélküli, lokális grounded generation részét.",
        project_area=("RAG", "Infrastruktúra"),
        related=("Qwen", "Streaming"),
    ),
    ReferenceEntry(
        "open_weight_model",
        "Open-weight modell",
        "Infrastruktúra",
        "Fogalom",
        "Olyan modell, amelynek súlyai letölthetők és lokálisan futtathatók a licencfeltételek szerint.",
        "A projekt lokális, kontrollálható és API-független LLM használatát teszi lehetővé.",
        project_area=("RAG", "Infrastruktúra"),
        related=("Ollama", "Kvantálás"),
    ),
    ReferenceEntry(
        "quantization",
        "Kvantálás",
        "Infrastruktúra",
        "Fogalom",
        "A modell súlyainak alacsonyabb numerikus precizitású reprezentációja a memória- és számítási igény csökkentésére.",
        "Kisebb GPU-n lehetővé teheti nagyobb modell lokális futtatását, minőségi és sebességbeli kompromisszumok mellett.",
        project_area=("Infrastruktúra", "RAG"),
        related=("VRAM", "Q4/Q8"),
    ),
    ReferenceEntry(
        "kv_cache",
        "KV cache",
        "Infrastruktúra",
        "Fogalom",
        "Transformer dekódolás során a korábbi tokenek attention key/value reprezentációinak gyorsítótára.",
        "Gyorsítja az autoregresszív generálást, de context hosszal és párhuzamossággal nő a memóriaigénye.",
        project_area=("Infrastruktúra", "RAG"),
        related=("Kontextusablak", "VRAM"),
    ),
]


def _strategy_entries() -> list[ReferenceEntry]:
    entries: list[ReferenceEntry] = []
    for key, chunking_meta in CHUNKING_STRATEGIES.items():
        entries.append(
            ReferenceEntry(
                key=f"chunking_{key}",
                name=f"{meta['name']} darabolás",
                category="Darabolás",
                kind="Stratégia",
                definition=str(meta["summary"]),
                why_it_matters=str(meta["best_for"]),
                interpretation=str(meta["how"]),
                project_area=("Darabolás", "Teljes pipeline benchmark"),
                related=("Chunk size", "Chunk overlap"),
                caveat=str(meta["tradeoff"]),
            )
        )
    for key, meta in RAG_STRATEGIES.items():
        entries.append(
            ReferenceEntry(
                key=f"rag_{key}",
                name=str(meta["name"]),
                category="RAG stratégiák",
                kind="Stratégia",
                definition=str(meta["summary"]),
                why_it_matters=str(meta["when"]),
                interpretation=f"Folyamat: {meta['flow']}",
                project_area=("RAG összehasonlítás", "Kiértékelés", "Teljes pipeline benchmark"),
                related=("Visszakeresés", "Context builder", "Grounded prompt"),
            )
        )
    for key, meta in CONTEXT_PROFILES.items():
        entries.append(
            ReferenceEntry(
                key=f"context_profile_{key}",
                name=f"Kontextusprofil: {meta['name']}",
                category="Kontextus és prompt",
                kind="Profil",
                definition=str(meta["summary"]),
                why_it_matters=f"Alapértelmezett evidence budget: {meta['budget']} token.",
                interpretation=str(meta["guidance"]),
                unit="token",
                project_area=("RAG játszótér", "RAG összehasonlítás"),
                related=("Context budget",),
            )
        )
    for key, meta in PROMPT_PROFILES.items():
        entries.append(
            ReferenceEntry(
                key=f"prompt_profile_{key}",
                name=f"Promptprofil: {meta['name']}",
                category="Kontextus és prompt",
                kind="Profil",
                definition=str(meta["summary"]),
                why_it_matters="A válasz szerkezetét és kommunikációs célját szabályozza anélkül, hogy a retrieval pipeline-t megváltoztatná.",
                interpretation=str(meta["instruction"]),
                project_area=("RAG játszótér", "Grounded prompt"),
                related=("Grounded prompt", "System prompt"),
            )
        )
    return entries


def all_reference_entries() -> list[ReferenceEntry]:
    entries = [*_BASE_ENTRIES, *_strategy_entries()]
    return sorted(entries, key=lambda item: (CATEGORY_ORDER.index(item.category), item.name.casefold()))


def filter_reference_entries(
    entries: Iterable[ReferenceEntry],
    *,
    query: str = "",
    categories: set[str] | None = None,
    kinds: set[str] | None = None,
    formulas_only: bool = False,
) -> list[ReferenceEntry]:
    normalized = query.strip().casefold()
    result: list[ReferenceEntry] = []
    for item in entries:
        if categories and item.category not in categories:
            continue
        if kinds and item.kind not in kinds:
            continue
        if formulas_only and not item.formula:
            continue
        haystack = " ".join(
            [
                item.name,
                item.category,
                item.kind,
                item.definition,
                item.why_it_matters,
                item.interpretation,
                " ".join(item.project_area),
                " ".join(item.related),
            ]
        ).casefold()
        if normalized and normalized not in haystack:
            continue
        result.append(item)
    return result


def reference_stats(entries: Iterable[ReferenceEntry]) -> dict[str, int]:
    items = list(entries)
    return {
        "entries": len(items),
        "metrics": sum(item.kind in {"Metrika", "Összetett metrika"} for item in items),
        "formulas": sum(bool(item.formula) for item in items),
        "strategies": sum(item.kind == "Stratégia" for item in items),
        "categories": len({item.category for item in items}),
    }


def reference_markdown(entries: Iterable[ReferenceEntry]) -> str:
    grouped: dict[str, list[ReferenceEntry]] = {}
    for item in entries:
        grouped.setdefault(item.category, []).append(item)

    lines = ["# Multi-RAG Engineering Lab – Fogalomtár és metrikák", ""]
    for category in CATEGORY_ORDER:
        items = grouped.get(category, [])
        if not items:
            continue
        lines.extend([f"## {category}", "", CATEGORY_DESCRIPTIONS.get(category, ""), ""])
        for item in items:
            lines.extend([f"### {item.name}", "", f"**Típus:** {item.kind}", "", item.definition, ""])
            lines.extend([f"**Miért fontos?** {item.why_it_matters}", ""])
            if item.interpretation:
                lines.extend([f"**Értelmezés:** {item.interpretation}", ""])
            if item.formula:
                lines.extend([f"**Képlet:** `${item.formula}$`", ""])
            if item.unit:
                lines.extend([f"**Egység / skála:** {item.unit}", ""])
            if item.caveat:
                lines.extend([f"**Korlát:** {item.caveat}", ""])
            if item.project_area:
                lines.extend([f"**Projektben:** {', '.join(item.project_area)}", ""])
            if item.related:
                lines.extend([f"**Kapcsolódó:** {', '.join(item.related)}", ""])
    return "\n".join(lines).strip() + "\n"
